# Unified Poisson Solver Testing
This notebook runs the unified test suites for Problem 1 (Table 1 & 2) as well as the complete NUDFT/NUFFT Accuracy Comparisons, tracking strictly $L_2$ relative errors and computational runtimes.

In [1]:
import os, sys
import pandas as pd
repo_root = r"C:\\Users\\charl\\OneDrive\\Documents\\GitHub\\Pyle_Daripa_Research"
os.chdir(repo_root)
if repo_root not in sys.path:
    sys.path.append(repo_root)

from Poisson_Solver_Testing_2.testing_helpers import (
    run_tests_pipeline,
    render_pivot,
    render_table2
)

## 1. Problem 1 Original Tables ($L_2$ Error & Time)

In [2]:
METHODS_P1 = [
    dict(name="Unif-FFT", label="Uniform / FFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=2, use_nudft=None),
    dict(name="Fixed-rand-NUDFT", label="Fixed rand / NUDFT", azu_unif=1, mesh_kind="rand", solver_azu_unif=1, use_nudft=True),
    dict(name="Fixed-rand-NUFFT", label="Fixed rand / NUFFT", azu_unif=1, mesh_kind="rand", solver_azu_unif=1, use_nudft=False),
]

N_vals_p1 = [64, 128, 256]
M_vals_p1 = [64, 128, 256]
N_fixed_p1 = 64

print("Running Problem 1 - Table 1...")
df_t1 = run_tests_pipeline(N_vals_p1, M_vals_p1, fixed_other=None, methods=METHODS_P1, test_type="P1_Table1")
print("\nRunning Problem 1 - Table 2...")
df_t2 = run_tests_pipeline(None, M_vals_p1, fixed_other=N_fixed_p1, methods=METHODS_P1, test_type="P1_Table2")

Running Problem 1 - Table 1...

Uniform / FFT
  N=  64, M=  64 | L2_rel=2.661e-06 | t=0.005s
  N=  64, M= 128 | L2_rel=6.548e-07 | t=0.004s
  N=  64, M= 256 | L2_rel=1.624e-07 | t=0.008s
  N= 128, M=  64 | L2_rel=2.661e-06 | t=0.002s
  N= 128, M= 128 | L2_rel=6.548e-07 | t=0.004s
  N= 128, M= 256 | L2_rel=1.624e-07 | t=0.009s
  N= 256, M=  64 | L2_rel=2.661e-06 | t=0.004s
  N= 256, M= 128 | L2_rel=6.548e-07 | t=0.008s
  N= 256, M= 256 | L2_rel=1.624e-07 | t=0.020s

Fixed rand / NUDFT
  N=  64, M=  64 | L2_rel=2.300e-06 | t=0.012s
  N=  64, M= 128 | L2_rel=5.736e-07 | t=0.020s
  N=  64, M= 256 | L2_rel=5.749e-07 | t=0.022s
  N= 128, M=  64 | L2_rel=1.241e-05 | t=0.091s
  N= 128, M= 128 | L2_rel=1.220e-05 | t=0.099s
  N= 128, M= 256 | L2_rel=1.207e-05 | t=0.105s
  N= 256, M=  64 | L2_rel=9.845e-02 | t=0.297s
  N= 256, M= 128 | L2_rel=9.848e-02 | t=0.321s
  N= 256, M= 256 | L2_rel=9.848e-02 | t=0.414s

Fixed rand / NUFFT
  N=  64, M=  64 | L2_rel=7.799e+03 | t=0.047s
  N=  64, M= 128 | L2_rel=7.767e+03 | t=0.065s
  N=  64, M= 256 | L2_rel=7.769e+03 | t=0.177s
  N= 128, M=  64 | L2_rel=5.095e+03 | t=0.064s
  N= 128, M= 128 | L2_rel=5.076e+03 | t=0.133s
  N= 128, M= 256 | L2_rel=5.071e+03 | t=0.352s
  N= 256, M=  64 | L2_rel=1.905e+03 | t=0.125s
  N= 256, M= 128 | L2_rel=1.890e+03 | t=0.329s
  N= 256, M= 256 | L2_rel=1.887e+03 | t=0.749s

Running Problem 1 - Table 2...

Uniform / FFT
  M=  64, Trapezoidal, Dirichlet | L2_rel=2.661e-06 | t=0.003s
  M=  64, Trapezoidal, Neumann | L2_rel=4.546e-05 | t=0.002s
  M=  64, Simpson, Dirichlet | L2_rel=4.023e-07 | t=0.009s
  M=  64, Simpson, Neumann | L2_rel=2.045e-07 | t=0.010s
  M= 128, Trapezoidal, Dirichlet | L2_rel=6.548e-07 | t=0.003s
  M= 128, Trapezoidal, Neumann | L2_rel=1.118e-05 | t=0.006s
  M= 128, Simpson, Dirichlet | L2_rel=5.085e-08 | t=0.018s
  M= 128, Simpson, Neumann | L2_rel=2.567e-08 | t=0.017s
  M= 256, Trapezoidal, Dirichlet | L2_rel=1.624e-07 | t=0.005s
  M= 256, Trapezoidal, Neumann | L2_rel=2.774e-06 | t=0.005s
  M= 256, Simpson, Dirichlet | L2_rel=6.388e-09 | t=0.036s
  M= 256, Simpson, Neumann | L2_rel=3.216e-09 | t=0.038s

Fixed rand / NUDFT
  M=  64, Trapezoidal, Dirichlet | L2_rel=2.300e-06 | t=0.010s
  M=  64, Trapezoidal, Neumann | L2_rel=1.437e-02 | t=0.007s
  M=  64, Simpson, Dirichlet | L2_rel=6.148e-07 | t=0.018s
  M=  64, Simpson, Neumann | L2_rel=1.437e-02 | t=0.031s
  M= 128, Trapezoidal, Dirichlet | L2_rel=5.736e-07 | t=0.014s
  M= 128, Trapezoidal, Neumann | L2_rel=1.437e-02 | t=0.014s
  M= 128, Simpson, Dirichlet | L2_rel=6.476e-07 | t=0.028s
  M= 128, Simpson, Neumann | L2_rel=1.437e-02 | t=0.027s
  M= 256, Trapezoidal, Dirichlet | L2_rel=5.749e-07 | t=0.029s
  M= 256, Trapezoidal, Neumann | L2_rel=1.437e-02 | t=0.024s
  M= 256, Simpson, Dirichlet | L2_rel=6.624e-07 | t=0.060s
  M= 256, Simpson, Neumann | L2_rel=1.437e-02 | t=0.049s

Fixed rand / NUFFT
  M=  64, Trapezoidal, Dirichlet | L2_rel=7.809e+03 | t=0.044s
  M=  64, Trapezoidal, Neumann | L2_rel=1.066e+03 | t=0.039s
  M=  64, Simpson, Dirichlet | L2_rel=7.814e+03 | t=0.064s
  M=  64, Simpson, Neumann | L2_rel=1.065e+03 | t=0.062s
  M= 128, Trapezoidal, Dirichlet | L2_rel=7.797e+03 | t=0.065s
  M= 128, Trapezoidal, Neumann | L2_rel=1.065e+03 | t=0.055s
  M= 128, Simpson, Dirichlet | L2_rel=7.797e+03 | t=0.076s
  M= 128, Simpson, Neumann | L2_rel=1.065e+03 | t=0.069s
  M= 256, Trapezoidal, Dirichlet | L2_rel=7.783e+03 | t=0.196s
  M= 256, Trapezoidal, Neumann | L2_rel=1.065e+03 | t=0.128s
  M= 256, Simpson, Dirichlet | L2_rel=7.793e+03 | t=0.185s
  M= 256, Simpson, Neumann | L2_rel=1.065e+03 | t=0.202s

In [3]:
for method in METHODS_P1:
    df_sub = df_t1[df_t1["name"] == method["name"]]
    render_pivot(df_sub, "N", "M", "L2_rel", f"{method['label']} - L2 Error (Table 1)")
    render_pivot(df_sub, "N", "M", "runtime", f"{method['label']} - Runtime (s) (Table 1)")

for method in METHODS_P1:
    df_sub = df_t2[df_t2["name"] == method["name"]]
    render_table2(df_sub, f"{method['label']} - Table 2 (N={N_fixed_p1})")

================================================================================
Uniform / FFT - L2 Error (Table 1)
================================================================================

================================================================================
Uniform / FFT - Runtime (s) (Table 1)
================================================================================

================================================================================
Fixed rand / NUDFT - L2 Error (Table 1)
================================================================================

================================================================================
Fixed rand / NUDFT - Runtime (s) (Table 1)
================================================================================

================================================================================
Fixed rand / NUFFT - L2 Error (Table 1)
================================================================================

================================================================================
Fixed rand / NUFFT - Runtime (s) (Table 1)
================================================================================

================================================================================
Uniform / FFT - Table 2 (N=64)
================================================================================
--- L2 Relative Error ---

--- Runtime (s) ---

================================================================================
Fixed rand / NUDFT - Table 2 (N=64)
================================================================================
--- L2 Relative Error ---

--- Runtime (s) ---

================================================================================
Fixed rand / NUFFT - Table 2 (N=64)
================================================================================
--- L2 Relative Error ---

--- Runtime (s) ---

## 2. NUDFT vs NUFFT vs FFT Accuracy Comparison

In [4]:
METHODS_COMP = [
    dict(name="Unif-FFT", label="Uniform / FFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=2, use_nudft=None),
    dict(name="Unif-NUDFT", label="Uniform / NUDFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=1, use_nudft=True),
    dict(name="Unif-NUFFT", label="Uniform / NUFFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=1, use_nudft=False),
]
for kind in ("rand", "jittered", "clustered", "sine"):
    METHODS_COMP += [
        dict(name=f"Fixed-{kind}-NUDFT", label=f"Fixed {kind} / NUDFT", azu_unif=1, mesh_kind=kind, solver_azu_unif=1, use_nudft=True),
        dict(name=f"Fixed-{kind}-NUFFT", label=f"Fixed {kind} / NUFFT", azu_unif=1, mesh_kind=kind, solver_azu_unif=1, use_nudft=False),
    ]

N_vals_c = [32, 64, 128]
M_vals_c = [32, 64, 128]
df_cN = run_tests_pipeline(N_vals_c, None, fixed_other=32, methods=METHODS_COMP, test_type="Accuracy_VaryN")
df_cM = run_tests_pipeline(None, M_vals_c, fixed_other=32, methods=METHODS_COMP, test_type="Accuracy_VaryM")

Uniform / FFT
  N=  32 | L2_rel=1.098e-05 | t=0.002s
  N=  64 | L2_rel=1.098e-05 | t=0.002s
  N= 128 | L2_rel=1.098e-05 | t=0.002s

Uniform / NUDFT
  N=  32 | L2_rel=1.098e-05 | t=0.005s
  N=  64 | L2_rel=1.098e-05 | t=0.007s

  N= 128 | L2_rel=1.098e-05 | t=0.086s

Uniform / NUFFT
  N=  32 | L2_rel=1.098e-05 | t=0.031s
  N=  64 | L2_rel=1.098e-05 | t=0.022s
  N= 128 | L2_rel=1.098e-05 | t=0.028s

Fixed rand / NUDFT
  N=  32 | L2_rel=1.099e-05 | t=0.004s
  N=  64 | L2_rel=1.057e-05 | t=0.005s
  N= 128 | L2_rel=1.646e-05 | t=0.070s

Fixed rand / NUFFT
  N=  32 | L2_rel=6.029e+08 | t=0.032s
  N=  64 | L2_rel=7.861e+03 | t=0.033s
  N= 128 | L2_rel=5.167e+03 | t=0.037s

Fixed jittered / NUDFT
  N=  32 | L2_rel=1.098e-05 | t=0.004s
  N=  64 | L2_rel=1.098e-05 | t=0.004s
  N= 128 | L2_rel=1.098e-05 | t=0.064s

Fixed jittered / NUFFT
  N=  32 | L2_rel=6.631e-01 | t=0.025s
  N=  64 | L2_rel=3.564e-01 | t=0.028s
  N= 128 | L2_rel=2.890e-01 | t=0.041s

Fixed clustered / NUDFT
  N=  32 | L2_rel=1.098e-05 | t=0.006s
  N=  64 | L2_rel=1.110e-05 | t=0.007s
  N= 128 | L2_rel=1.129e-05 | t=0.092s

Fixed clustered / NUFFT
  N=  32 | L2_rel=4.827e+07 | t=0.029s
  N=  64 | L2_rel=4.058e+04 | t=0.036s
  N= 128 | L2_rel=1.008e+03 | t=0.047s

Fixed sine / NUDFT
  N=  32 | L2_rel=1.099e-05 | t=0.003s
  N=  64 | L2_rel=1.309e-05 | t=0.004s
  N= 128 | L2_rel=1.198e-05 | t=0.072s

Fixed sine / NUFFT
  N=  32 | L2_rel=4.500e-03 | t=0.031s
  N=  64 | L2_rel=1.385e-03 | t=0.041s
  N= 128 | L2_rel=2.956e-04 | t=0.056s

Uniform / FFT
  M=  32 | L2_rel=1.098e-05 | t=0.001s
  M=  64 | L2_rel=2.661e-06 | t=0.001s
  M= 128 | L2_rel=6.548e-07 | t=0.002s

Uniform / NUDFT
  M=  32 | L2_rel=1.098e-05 | t=0.003s
  M=  64 | L2_rel=2.661e-06 | t=0.004s
  M= 128 | L2_rel=6.548e-07 | t=0.007s

Uniform / NUFFT
  M=  32 | L2_rel=1.098e-05 | t=0.020s
  M=  64 | L2_rel=2.661e-06 | t=0.025s
  M= 128 | L2_rel=6.548e-07 | t=0.028s

Fixed rand / NUDFT
  M=  32 | L2_rel=1.099e-05 | t=0.004s
  M=  64 | L2_rel=2.661e-06 | t=0.005s
  M= 128 | L2_rel=6.549e-07 | t=0.008s

Fixed rand / NUFFT
  M=  32 | L2_rel=5.811e+08 | t=0.032s
  M=  64 | L2_rel=1.482e+09 | t=0.035s
  M= 128 | L2_rel=5.657e+08 | t=0.067s

Fixed jittered / NUDFT
  M=  32 | L2_rel=1.098e-05 | t=0.004s
  M=  64 | L2_rel=2.660e-06 | t=0.005s
  M= 128 | L2_rel=6.547e-07 | t=0.008s

Fixed jittered / NUFFT
  M=  32 | L2_rel=6.631e-01 | t=0.031s
  M=  64 | L2_rel=6.579e-01 | t=0.037s
  M= 128 | L2_rel=6.566e-01 | t=0.042s

Fixed clustered / NUDFT
  M=  32 | L2_rel=1.098e-05 | t=0.003s
  M=  64 | L2_rel=2.661e-06 | t=0.004s
  M= 128 | L2_rel=6.599e-07 | t=0.009s

Fixed clustered / NUFFT
  M=  32 | L2_rel=4.838e+07 | t=0.037s
  M=  64 | L2_rel=4.770e+07 | t=0.036s
  M= 128 | L2_rel=4.746e+07 | t=0.056s

Fixed sine / NUDFT
  M=  32 | L2_rel=1.099e-05 | t=0.003s
  M=  64 | L2_rel=2.661e-06 | t=0.006s
  M= 128 | L2_rel=6.549e-07 | t=0.009s

Fixed sine / NUFFT
  M=  32 | L2_rel=4.500e-03 | t=0.032s
  M=  64 | L2_rel=4.502e-03 | t=0.028s
  M= 128 | L2_rel=4.502e-03 | t=0.038s

In [5]:
render_pivot(df_cN, "N", "label", "L2_rel", "Accuracy Comp (Fixed M=32) - L2 Error")
render_pivot(df_cN, "N", "label", "runtime", "Accuracy Comp (Fixed M=32) - Runtime (s)")

render_pivot(df_cM, "M", "label", "L2_rel", "Accuracy Comp (Fixed N=32) - L2 Error")
render_pivot(df_cM, "M", "label", "runtime", "Accuracy Comp (Fixed N=32) - Runtime (s)")

================================================================================
Accuracy Comp (Fixed M=32) - L2 Error
================================================================================

================================================================================
Accuracy Comp (Fixed M=32) - Runtime (s)
================================================================================

================================================================================
Accuracy Comp (Fixed N=32) - L2 Error
================================================================================

================================================================================
Accuracy Comp (Fixed N=32) - Runtime (s)
================================================================================