# Unified Poisson Solver Testing
This notebook runs the unified test suites for Problem 1 (Table 1 & 2) as well as the complete NUDFT/NUFFT Accuracy Comparisons, tracking strictly $L_2$ relative errors and computational runtimes.

In [1]:
import os, sys
import pandas as pd
# Main project root
repo_root = r"C:\Users\charl\OneDrive\Documents\GitHub\NUFFTRR_Poisson"
os.chdir(repo_root)
if repo_root not in sys.path:
    sys.path.append(repo_root)

from Tests.CPU.testing_helpers import (
    run_tests_pipeline,
    render_accuracy,
    render_runtime,
    render_table2_accuracy,
    render_table2_runtime
)

# Setup

In [2]:
N_vals_p0 = [32, 64, 128, 256, 512]
M_vals_p0 = [32, 64, 128, 256, 512]
N_fixed_p0 = 32

N_vals_p1 = [32, 64, 128, 256, 512]
M_vals_p1 = [32, 64, 128, 256, 512]
N_fixed_p1 = 32

N_vals_c = [32, 64, 128, 256, 512]
M_vals_c = [32, 64, 128, 256, 512]

MUTE_OUTPUT = True

# Run Problems

In [3]:
METHODS_P0 = [
    dict(name="Unif-FFT", label="Uniform / FFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=2, use_nudft=None),
    dict(name="Fixed-jittered-NUDFT", label="Fixed jittered / NUDFT", azu_unif=1, mesh_kind="jittered", solver_azu_unif=1, use_nudft=True),
    dict(name="Fixed-jittered-NUFFT", label="Fixed jittered / NUFFT", azu_unif=1, mesh_kind="jittered", solver_azu_unif=1, use_nudft=False),
]

METHODS_P1 = [
    dict(name="Unif-FFT", label="Uniform / FFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=2, use_nudft=None),
    dict(name="Fixed-rand-NUDFT", label="Fixed rand / NUDFT", azu_unif=1, mesh_kind="rand", solver_azu_unif=1, use_nudft=True),
    dict(name="Fixed-rand-NUFFT", label="Fixed rand / NUFFT", azu_unif=1, mesh_kind="rand", solver_azu_unif=1, use_nudft=False),
]

METHODS_COMP = [
    dict(name="Unif-FFT", label="Uniform / FFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=2, use_nudft=None),
    dict(name="Unif-NUDFT", label="Uniform / NUDFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=1, use_nudft=True),
    dict(name="Unif-NUFFT", label="Uniform / NUFFT", azu_unif=2, mesh_kind="uniform", solver_azu_unif=1, use_nudft=False),
]
for kind in ("rand", "jittered", "clustered", "sine"):
    METHODS_COMP += [
        dict(name=f"Fixed-{kind}-NUDFT", label=f"Fixed {kind} / NUDFT", azu_unif=1, mesh_kind=kind, solver_azu_unif=1, use_nudft=True),
        dict(name=f"Fixed-{kind}-NUFFT", label=f"Fixed {kind} / NUFFT", azu_unif=1, mesh_kind=kind, solver_azu_unif=1, use_nudft=False),
    ]

print("Running Problem 0 - Table 1 (Jittered)...")
df_p0_t1 = run_tests_pipeline(N_vals_p0, M_vals_p0, fixed_other=None, methods=METHODS_P0, test_type="P1_Table1",mute=MUTE_OUTPUT)
print("\nRunning Problem 0 - Table 2 (Jittered)...")
df_p0_t2 = run_tests_pipeline(None, M_vals_p0, fixed_other=N_fixed_p0, methods=METHODS_P0, test_type="P1_Table2",mute=MUTE_OUTPUT)

print("Running Problem 1 - Table 1 (Rand)...")
df_t1 = run_tests_pipeline(N_vals_p1, M_vals_p1, fixed_other=None, methods=METHODS_P1, test_type="P1_Table1",mute=MUTE_OUTPUT)
print("\nRunning Problem 1 - Table 2 (Rand)...")
df_t2 = run_tests_pipeline(None, M_vals_p1, fixed_other=N_fixed_p1, methods=METHODS_P1, test_type="P1_Table2",mute=MUTE_OUTPUT)


print("Running Accuracy Comparisons...")
df_cN = run_tests_pipeline(N_vals_c, None, fixed_other=32, methods=METHODS_COMP, test_type="Accuracy_VaryN", mute=MUTE_OUTPUT)
df_cM = run_tests_pipeline(None, M_vals_c, fixed_other=32, methods=METHODS_COMP, test_type="Accuracy_VaryM", mute=MUTE_OUTPUT)
print("Done.")

Running Problem 0 - Table 1 (Jittered)...

Running Problem 0 - Table 2 (Jittered)...
Running Problem 1 - Table 1 (Rand)...

Running Problem 1 - Table 2 (Rand)...
Running Accuracy Comparisons...
Done.

# Accuracy

In [4]:
print("--- ACCURACY SECTION ---")

print("Problem 0 - Table 1 - errors should be the same for rows, and decrease along columns. uniform, nudft, and nufft should be same")
render_accuracy(df_p0_t1, index_col="N", columns_col=["label", "M"], title_prefix="Problem 0 - Table 1")
print("error along rows indicate nudft or nufft is not currently accurate enough")

print("Problem 0 - Table 2 - errors should decrease along rows")
render_table2_accuracy(df_p0_t2, title_prefix=f"Problem 0 - Table 2 (N={N_fixed_p0})")
print("Neumann error for nudft and nufft being constant is an issue. this is either with zero mode or handling fourier coeffs.")

print("Problem 1 - Table 1 - errors should be the same for rows, and decrease along columns. uniform, nudft, and nufft should be same")
render_accuracy(df_t1, index_col="N", columns_col=["label", "M"], title_prefix="Problem 1 - Table 1")
print("error along rows indicate nudft or nufft is not currently accurate enough. Inaccuracy is worse than Problem 0, likely due to random mesh being more challenging than jittered.")

print("Problem 1 - Table 2 - errors should decrease along rows")
render_table2_accuracy(df_t2, title_prefix=f"Problem 1 - Table 2 (N={N_fixed_p1})")
print("for nonuniform case dirichlet and neumann errors being constant is concerning. Indicates either mode issue or accuracy issues with algorithm")

print("Problem 2 - Table 1 -All errors should be same along rows, and relatively same along columns")
render_accuracy(df_cN, index_col="N", columns_col="label", title_prefix="Accuracy Comparison (Fixed M=32)")
print("errors for diff meshes getting worse suggests nudft or nufft not accurate")

print("Problem 2 - Table 2 -All errors should decrease along rows, and relatively same along columns")
render_accuracy(df_cM, index_col="M", columns_col="label", title_prefix="Accuracy Comparison (Fixed N=32)")
print("errors for diff meshes getting worse suggests nudft or nufft not accurate")

--- ACCURACY SECTION ---
Problem 0 - Table 1 - errors should be the same for rows, and decrease along columns. uniform, nudft, and nufft should be same

================================================================================
Problem 0 - Table 1 Accuracy
================================================================================

error along rows indicate nudft or nufft is not currently accurate enough
Problem 0 - Table 2 - errors should decrease along rows

================================================================================
Problem 0 - Table 2 (N=32) Accuracy
================================================================================

Neumann error for nudft and nufft being constant is an issue. this is either with zero mode or handling fourier coeffs.
Problem 1 - Table 1 - errors should be the same for rows, and decrease along columns. uniform, nudft, and nufft should be same

================================================================================
Problem 1 - Table 1 Accuracy
================================================================================

error along rows indicate nudft or nufft is not currently accurate enough. Inaccuracy is worse than Problem 0, likely due to random mesh being more challenging than jittered.
Problem 1 - Table 2 - errors should decrease along rows

================================================================================
Problem 1 - Table 2 (N=32) Accuracy
================================================================================

for nonuniform case dirichlet and neumann errors being constant is concerning. Indicates either mode issue or accuracy issues with algorithm
Problem 2 - Table 1 -All errors should be same along rows, and relatively same along columns

================================================================================
Accuracy Comparison (Fixed M=32) Accuracy
================================================================================

errors for diff meshes getting worse suggests nudft or nufft not accurate
Problem 2 - Table 2 -All errors should decrease along rows, and relatively same along columns

================================================================================
Accuracy Comparison (Fixed N=32) Accuracy
================================================================================

errors for diff meshes getting worse suggests nudft or nufft not accurate

# Runtimes

In [5]:
print("--- RUNTIME SECTION ---")
render_runtime(df_p0_t1, index_col="N", columns_col=["label", "M"], title_prefix="Problem 0 (Jittered) Table 1")
render_table2_runtime(df_p0_t2, title_prefix=f"Problem 0 (Jittered) Table 2 (N={N_fixed_p0})")

render_runtime(df_t1, index_col="N", columns_col=["label", "M"], title_prefix="Problem 1 (Rand) Table 1")
render_table2_runtime(df_t2, title_prefix=f"Problem 1 (Rand) Table 2 (N={N_fixed_p1})")

render_runtime(df_cN, index_col="N", columns_col="label", title_prefix="Accuracy Comparison (Fixed M=32)")
render_runtime(df_cM, index_col="M", columns_col="label", title_prefix="Accuracy Comparison (Fixed N=32)")

--- RUNTIME SECTION ---

================================================================================
Problem 0 (Jittered) Table 1 Runtime (s)
================================================================================

================================================================================
Problem 0 (Jittered) Table 2 (N=32) Runtime (s)
================================================================================

================================================================================
Problem 1 (Rand) Table 1 Runtime (s)
================================================================================

================================================================================
Problem 1 (Rand) Table 2 (N=32) Runtime (s)
================================================================================

================================================================================
Accuracy Comparison (Fixed M=32) Runtime (s)
================================================================================

================================================================================
Accuracy Comparison (Fixed N=32) Runtime (s)
================================================================================